# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZQ28VRNOKZAYxIelrfy7Et3so-vVLiQt
"""



import pandas as pd
markaz={
    "FISH":["Abdusalimov Muhammadali","Abdusalimova Oygul","Abdusalimova Xushnoza","Abdusalimov Nurimuhammad","Abdusalimov Nuriislom"],
    "Yoshi":["18","20","24","21","17"],
    "Manzili":["Farg'ona shahar","Vodil shahri","Mindonobod shahar","Yoshlarobod qishlog'i","Yangiobod qishlog'i"],
    "Jinsi":["Erkak","ayol","ayol","Erkak","Erkak"],
    "Universiteti":["TATUFF","FARDU","FARPI","FARPI","TDIU"],

}
db=pd.DataFrame (markaz)
print(db)

filtr=db[db["Jinsi"]=="ayol"]
print(filtr)

filtr=db[db["Universiteti"]=="FARPI"]
print(filtr)

filtr=db[(db["Jinsi"]=="ayol")& (db["Yoshi"]>"19")]
print(filtr)

